order/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('order.views',
    url(r'^(?P<order_id>\d+)/$', 'detail', name='order-detail'),
    url(r'^generate/$', 'generate', name='order-generate'),
    
    url(r'^item/add/$', 'add_item', name='order-item-add'),
    url(r'^item/(?P<product_id>\d+)/remove/$', 'remove_item', name='order-item-remove'),
)

urlpatterns += (
    url(r'^cart/$', 'django.views.generic.simple.direct_to_template', {'template': 'order/shop_cart.html'}, name="order-shop-cart"),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django import template
template.add_to_builtins('common.mytags')


urlpatterns = patterns('',
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
     url(r'^admin/', include(admin.site.urls)),
     
    # home 
    url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}, name='home'),
    
    url(r'^account/', include('account.urls')),
    
    url(r'^product/list/$', 'product.views.list_product', name='product-list'),
)

order/models.py
#coding: utf-8

from django.db import models
from django.contrib.auth.models import User

from product.models import Product


ORDER_STATUS = (('1', u'新提交'),
                  ('2', u'商品出库'),
                  ('3', u'等待收货'),
                  ('4', u'完成'),
                  )

class Order(models.Model):
    amount = models.FloatField(u'总价')
    owner = models.ForeignKey(User, verbose_name=u'客户')
    created_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    status = models.CharField(u'状态', max_length=1, choices=ORDER_STATUS, default='1')
    address = models.TextField(u'送货地址')
    description = models.TextField(u'额外说明', blank=True, null=True)
    
    class Meta:
        db_table = 'order'
        verbose_name = u'订单'
        verbose_name_plural = u'订单'
        app_label = u'客户订单'
    
    def __unicode__(self):
        return self.number

    @property
    def number(self):
        return 'OSN-%d' % self.id
    
    @property
    def is_new(self):
        return '1' == self.status


class OrderItem(models.Model):
    product = models.ForeignKey(Product, verbose_name=u'订购商品')
    price = models.FloatField(u'单价')
    count = models.PositiveIntegerField(u'数量')
    order = models.ForeignKey(Order, verbose_name=u'订单编号')
    
    class Meta:
        db_table = 'order_item'
        verbose_name = u'所购商品'
        verbose_name_plural = u'所购商品'
    
    def __unicode__(self):
        return self.product.name
    
    @property
    def amount(self):
        return self.count * self.price
    

order/forms.py
#coding: utf-8

from django.conf import settings


class ShoppingCartForm:
    """
    Not use classic Django form for less cache in session.
    Use this to display shopping card and store in session.
    item format: {
                    product_id: {
                        'name': product_name,
                        'count': count,
                        'price': price,
                    },
                }
    """
    def __init__(self, request):
#        del request.session[settings.SHOP_CART_KEY]
        cached = request.session.get(settings.SHOP_CART_KEY)
        if cached:
            self.products = cached['products']
            self.amount = cached['amount']
        else:
            self.products = {}
            self.amount = 0

    def remove_product(self, product_id):
        if self.products.has_key(product_id):
            del self.products[product_id]
    
    def set_product(self, product, count):
        self.products['%s' % product.id] = {'name': product.name,
                                     'count': count,
                                     'price': product.price,
                                     'amount': count * product.price,
                                     'thumbnail': str(product.image)}
        
    def update_price(self):
        self.amount = 0
        for p in self.products.itervalues():
            self.amount += p['amount']
    
    def store(self, request):
        self.update_price()
        request.session[settings.SHOP_CART_KEY] = {'amount': self.amount,
                                                   'products': self.products}
    
    def delete(self, request):
        try:
            del request.session[settings.SHOP_CART_KEY]
        except:
            pass
        

order/views.py
#coding: utf-8

from django import shortcuts
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import transaction

from account.models import ContactAddress
from product.models import Product
from order.models import Order, OrderItem
from order.forms import ShoppingCartForm


@login_required
def my_order(request):
    return shortcuts.render_to_response('order/list.html',
                    {'orders': Order.objects.all()},
                    context_instance=RequestContext(request))
    

@login_required
def generate(request):
    if request.POST:
        cart = ShoppingCartForm(request)
        address_id = request.POST.get('address', '')
        if not address_id:
            messages.error(request, u'请选择一个送货地址。')
            return shortcuts.redirect(reverse('order-generate'))
        address = shortcuts.get_object_or_404(ContactAddress, id=address_id, user=request.user)
        
        with transaction.commit_on_success():
            order = Order(owner=request.user,
                          address=str(address),
                          description=request.POST.get('description', ''),
                          amount=cart.amount)
            order.save()
            
            for pid, p in cart.products.iteritems():
                OrderItem(order=order,
                           product=shortcuts.get_object_or_404(Product, id=pid),
                           price=p['price'],
                           count=p['count']
                           ).save()
                           
            cart.delete(request)
            messages.success(request, u'下单成功！请等待系统确认。')
            return shortcuts.redirect(reverse('order-detail', args=[order.id]))
    
    addresses = ContactAddress.objects.filter(user=request.user)
    if not addresses:
        messages.error(request, u'你还没有送货地址，请创建至少一个送货地址。')
        return shortcuts.redirect(reverse('account-address-add'))
    
    return shortcuts.render_to_response('order/generate.html',
                    {'addresses': addresses},
                    context_instance=RequestContext(request))


def detail(request, order_id):
    order = shortcuts.get_object_or_404(Order, id=order_id)
    return shortcuts.render_to_response('order/detail.html',
                    {'order': order},
                    context_instance=RequestContext(request))
    

def add_item(request):
    product_id = request.REQUEST.get('pid', '')
    try:
        count = int(request.REQUEST.get('count', '1'))
        if count < 1:
            raise
    except:
        messages.error(request, u'您输入的商品数量错误，请重新输入。')
        return shortcuts.render_to_response('order/shop_cart.html',
                    context_instance=RequestContext(request))
    
    product = shortcuts.get_object_or_404(Product, id=product_id)
    
    cart = ShoppingCartForm(request)
    cart.set_product(product, count)
    cart.store(request)
    
    return shortcuts.render_to_response('order/shop_cart.html',
                    context_instance=RequestContext(request))


def remove_item(request, product_id):
    cart = ShoppingCartForm(request)
    cart.remove_product(product_id)
    cart.store(request)
    
    return shortcuts.render_to_response('order/shop_cart.html',
                    context_instance=RequestContext(request))
    

templates/order/detail.html
{% extends 'account/_base.html' %}

{% block order_nav %}class="active"{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
        <h3>订单详情</h3>
    </div>
    {% if order.is_new %}
    <div class="span6">
        <a class="btn btn-danger pull-right" href="{% url order-detail order.id %}">取消订单</a>
    </div>
    {% endif %}
</div>

<hr>
<p>
    <span class="muted">编号：</span> {{ order.number }}
</p>
<p>
    <span class="muted">状态：</span> <span class="text-success">{{ order.get_status_display }}</span>
</p>
<p>
    <span class="muted">建于：</span> {{ order.created_time }}
</p>
<p>
    <strong><span>总计：</span> <span class="text-error">{{ order.amount|asmoney }}</span></strong>
</p>
<p>
    <span class="muted">送货地址：</span> {{ order.address }}
</p>
{% if order.description %}
<p>
    <span style="vertical-align:top;" class="muted">额外说明：</span>
    <textarea disabled rows="3" class="span5">{{ order.description }}</textarea>
</p>
{% endif %}

<hr>
{% for item in order.orderitem_set.select_related %}
    <div class="row-fluid">
        <div class="span2">
            <a href="{% url product-detail item.product.id %}">
                <img class="thumb-img-cart img-rounded" src="/static/{{ item.product.image }}">
            </a>
        </div>
        <div class="span5">
            <a href="{% url product-detail item.product.id %}">{{ item.product.name }}</a>
            <br> <span class="label">{{ item.price|asmoney }}</span>
        </div>
        <div class="span2">
            {{ item.count }}
        </div>
        <div class="span2">
            <span class="text-error">{{ item.amount|asmoney }}</span>
        </div>
    </div>
    {% if not forloop.last %}
        <hr>
    {% endif %}
{% endfor %}

{% endblock %}

templates/order/generate.html
{% extends '_base.html' %}

{% block content %}

<form action="{% url order-generate %}" method="POST">{% csrf_token %}
<h3>请确认订单内容</h3>

<hr>
<strong>请选择送货地址：</strong>
<p>
{% for addr in addresses %}
    <label class="radio">
        <input type="radio" name="address" value="{{ addr.id }}"{% if addr.is_default %} checked{% endif %}> {{ addr }}
    </label>
{% endfor %}
</p>

<hr>
订单说明：
<p>
<textarea rows="3" class="span5" name="description" placeholder="比如送货要求：请于周末下午送货。"></textarea>
</p>

<hr>
{% for pid, p in shop_cart.products.items %}
    <div class="row-fluid">
        <div class="span2">
            <a href="{% url product-detail pid %}">
                <img class="thumb-img-cart img-rounded" src="/static/{{ p.thumbnail }}">
            </a>
        </div>
        <div class="span5">
            <a href="{% url product-detail pid %}">{{ p.name }}</a>
            <br> <span class="label">{{ p.price|asmoney }}</span>
        </div>
        <div class="span2">
            {{ p.count }}
        </div>
        <div class="span2">
            <strong><span class="text-error">{{ p.amount|asmoney }}</span></strong>
        </div>
    </div>
    <hr>
{% empty %}
    <p class="muted">
                            你还没有订购商品。<a class="btn btn-primary" href="{% url product-list %}">马上去购物</a>
    </p>
{% endfor %}
<p class="lead">
    <strong class="pull-right">总计：<span class="text-error">{{ shop_cart.amount|asmoney }}</span></strong>
</p>
<div class="clearfix"></div>

<hr>
<div>
    <a class="btn pull-left" href="{% url order-shop-cart %}">&laquo;上一步</a>
    <button class="btn btn-large btn-primary pull-right" type="submit">生成订单</button>
</div>
</form>

{% endblock %}

templates/order/list.html
{% extends 'account/_base.html' %}

{% block order_nav %}class="active"{% endblock %}

{% block content %}

<h3>订单列表</h3>
<hr>

{% for o in orders %}
    <div class="row-fluid">
        <div class="span2">
            <a href="{% url order-detail o.id %}"> {{ o.number }} </a>
        </div>
        <div class="span2 text-success">
            {{ o.get_status_display }}
        </div>
        <div class="span3">
            {{ o.created_time }}
        </div>
        <div class="span3">
            {{ o.amount|asmoney }}
        </div>
        <div class="2">
            <a class="btn" href="{% url order-detail o.id %}">详细情况</a>
        </div>
    </div>
    {% if not forloop.last %}
        <hr>
    {% endif %}
{% empty %}
<p class="muted">
                        你还没有订购过商品。<a class="btn btn-primary" href="{% url product-list %}">马上去购物&raquo;</a>
</p>
{% endfor %}

{% endblock %}

templates/order/shop_cart.html
{% extends '_base.html' %}

{% block content %}

<h3>我的购物车</h3>
<hr>
{% for pid, p in shop_cart.products.items %}
    <div class="row-fluid">
        <div class="span2">
            <a href="{% url product-detail pid %}">
                <img class="thumb-img-cart img-rounded" src="/static/{{ p.thumbnail }}">
            </a>
        </div>
        <div class="span3">
            <a href="{% url product-detail pid %}">{{ p.name }}</a>
            <br> <span class="label">{{ p.price|asmoney }}</span>
        </div>
        <div class="span3">
            <form action="{% url order-item-add %}" method="POST">{% csrf_token %}
                <input type="hidden" value="{{ pid }}" name="pid">
                <div class="input-append">
                  <input value="{{ p.count }}" class="input-mini" name="count" type="text">
                  <button class="btn" type="submit">更新数量</button>
                </div>
            </form>
        </div>
        <div class="span2">
            <strong><span class="text-error">{{ p.amount|asmoney }}</span></strong>
        </div>
        <div class="span2">
            <a href="{% url order-item-remove pid %}" class="btn btn-danger">删除</a>
        </div>
    </div>
    <hr>
{% empty %}
    <p class="muted">
                            你还没有订购商品。<a class="btn btn-primary" href="{% url product-list %}">马上去购物&raquo;</a>
    </p>
{% endfor %}

{% if shop_cart.products %}
<p class="lead">
    <strong class="pull-right">总计：<span class="text-error">{{ shop_cart.amount|asmoney }}</span></strong>
</p>
<div class="clearfix"></div>

<hr>
<div>
    <a class="btn pull-left" href="{% url product-list %}">继续购物</a>
    <a class="btn btn-large btn-primary pull-right" href="{% url order-generate %}">现在去结算&raquo;</a>
</div>
{% endif %}

{% endblock %}